name: hello-world action
on: [push]
jobs:
  Say-Hello-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Hello, World!"
      # Так не работает. Почему? 🤔
      # - run: make say-hello
