name: hello-world action
on: push
jobs:
  Say-Hello-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make say-hello
